### ISSUE TITLE
function:wifi_scan_result_printer,can't print ssid info

### ISSUE THREAD

**Issue by daxinxin233** [mongoose-os-libs/rpc-service-wifi#1]
file:mgos_rpc_service_wifi.c,
line:19
code: for (int i = 0; i < num_res; i++, res++)
i delete "res++",and normally print ssid info.

**Comment by kzyapkov** [comment]
@rojer :)

**Comment by rojer** [comment]
fixed by https://github.com/mongoose-os-libs/rpc-service-wifi/commit/4ec60411e66a8460314dfb60db1254887b36b815
